project_name: event-generator
before:
  hooks:
    - make prepare
builds:
  - id: "event-generator"
    goos:
    - linux
    goarch:
    - amd64
    - arm
    - arm64
    - 386
    main: .
    env:
      - CGO_ENABLED=0
      - DOCKER_CLI_EXPERIMENTAL: "enabled"
    binary: event-generator

dockers:
  - use: Buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "avinashyadavpuresoftware/event-generator:latest"
      - "avinashyadavpuresoftware/event-generator:{{ .Version }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - .git
      - cmd
      - pkg
      - events
      - tools
      - go.mod
      - go.sum
      - main.go
      - Makefile

  - use: Buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - "avinashyadavpuresoftware/event-generator:latest-arm64"
      - "avinashyadavpuresoftware/event-generator:{{ .Version }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - .git
      - cmd
      - pkg
      - events
      - tools
      - go.mod
      - go.sum
      - main.go
      - Makefile
      
release:
  github:
  prerelease: auto
