name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t avi:latest .
  test_arm64: 
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Install and Run tests
        run: |
               docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
               arm64v8/ubuntu:20.04 \
               bash -exc 'apt-get update -y && \
                 apt-get install cmake -y && \
                 apt install build-essential -y'
      - name: Setup buildx
        uses: docker/setup-Buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: avinashyadavpuresoftware
          password: Avinash@8794
      - name: Build and Publish API
        uses: docker/build-push-action@v2
        with:
         context: .
         file: ./Dockerfile
         platforms: linux/arm64
         push: true
         tags: avinashyadavpuresoftware/imaggg5:latest
